[package]
name = "dynamic-tic-tac-toe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
csbindgen = "1.9.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

